# Generated by Django 6.0 on 2026-01-04 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_id', models.TextField(blank=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('display_pic', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'ordering': ['created'],
            },
        ),
    ]
